//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace BookClient.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "book", Namespace = "http://schemas.datacontract.org/2004/07/BookServer.Models")]
    public partial class Book : object
    {
        
        private string[] authorsField;
        
        private string genreField;
        
        private string isbnField;
        
        private System.DateTime publishDateField;
        
        private string titleField;


        [System.Runtime.Serialization.DataMemberAttribute(Name = "authors")]
        public string[] Authors
        {
            get
            {
                return this.authorsField;
            }
            set
            {
                this.authorsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Name = "genre")]
        public string Genre
        {
            get
            {
                return this.genreField;
            }
            set
            {
                this.genreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Name = "isbn")]
        public string ISBN
        {
            get
            {
                return this.isbnField;
            }
            set
            {
                this.isbnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="publishDate")]
        public System.DateTime PublishDate
        {
            get
            {
                return this.publishDateField;
            }
            set
            {
                this.publishDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="title")]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
}
namespace BookServer.Services
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BooksResponse", Namespace="http://schemas.datacontract.org/2004/07/BookServer.Services")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BookServer.Services.CreateBookResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BookServer.Services.GetBookResponse))]
    public partial class BooksResponse : object
    {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateBookResponse", Namespace="http://schemas.datacontract.org/2004/07/BookServer.Services")]
    public partial class CreateBookResponse : BookServer.Services.BooksResponse
    {
        
        private BookClient.Data.Book BookField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookClient.Data.Book Book
        {
            get
            {
                return this.BookField;
            }
            set
            {
                this.BookField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBookResponse", Namespace="http://schemas.datacontract.org/2004/07/BookServer.Services")]
    public partial class GetBookResponse : BookServer.Services.BooksResponse
    {
        
        private BookClient.Data.Book BookField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookClient.Data.Book Book
        {
            get
            {
                return this.BookField;
            }
            set
            {
                this.BookField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBooks")]
public interface IBooks
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBooks/GetBooks", ReplyAction="http://tempuri.org/IBooks/GetBooksResponse")]
    System.IAsyncResult BeginGetBooks(System.AsyncCallback callback, object asyncState);
    
    BookClient.Data.Book[] EndGetBooks(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBooks/GetBook", ReplyAction="http://tempuri.org/IBooks/GetBookResponse")]
    System.IAsyncResult BeginGetBook(string isbn, System.AsyncCallback callback, object asyncState);
    
    BookServer.Services.GetBookResponse EndGetBook(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBooks/Search", ReplyAction="http://tempuri.org/IBooks/SearchResponse")]
    System.IAsyncResult BeginSearch(string searchText, System.AsyncCallback callback, object asyncState);
    
    BookClient.Data.Book[] EndSearch(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBooks/UpdateBook", ReplyAction="http://tempuri.org/IBooks/UpdateBookResponse")]
    System.IAsyncResult BeginUpdateBook(BookClient.Data.Book book, System.AsyncCallback callback, object asyncState);
    
    BookServer.Services.BooksResponse EndUpdateBook(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBooks/DeleteBook", ReplyAction="http://tempuri.org/IBooks/DeleteBookResponse")]
    System.IAsyncResult BeginDeleteBook(string isbn, System.AsyncCallback callback, object asyncState);
    
    BookServer.Services.BooksResponse EndDeleteBook(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBooks/CreateBook", ReplyAction="http://tempuri.org/IBooks/CreateBookResponse")]
    System.IAsyncResult BeginCreateBook(BookClient.Data.Book book, System.AsyncCallback callback, object asyncState);
    
    BookServer.Services.CreateBookResponse EndCreateBook(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBooks/Login", ReplyAction="http://tempuri.org/IBooks/LoginResponse")]
    System.IAsyncResult BeginLogin(System.AsyncCallback callback, object asyncState);
    
    string EndLogin(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBooksChannel : IBooks, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public BookClient.Data.Book[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((BookClient.Data.Book[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public BookServer.Services.GetBookResponse Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((BookServer.Services.GetBookResponse)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public BookClient.Data.Book[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((BookClient.Data.Book[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UpdateBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public UpdateBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public BookServer.Services.BooksResponse Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((BookServer.Services.BooksResponse)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DeleteBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public DeleteBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public BookServer.Services.BooksResponse Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((BookServer.Services.BooksResponse)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CreateBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public CreateBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public BookServer.Services.CreateBookResponse Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((BookServer.Services.CreateBookResponse)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BooksClient : System.ServiceModel.ClientBase<IBooks>, IBooks
{
    
    private BeginOperationDelegate onBeginGetBooksDelegate;
    
    private EndOperationDelegate onEndGetBooksDelegate;
    
    private System.Threading.SendOrPostCallback onGetBooksCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetBookDelegate;
    
    private EndOperationDelegate onEndGetBookDelegate;
    
    private System.Threading.SendOrPostCallback onGetBookCompletedDelegate;
    
    private BeginOperationDelegate onBeginSearchDelegate;
    
    private EndOperationDelegate onEndSearchDelegate;
    
    private System.Threading.SendOrPostCallback onSearchCompletedDelegate;
    
    private BeginOperationDelegate onBeginUpdateBookDelegate;
    
    private EndOperationDelegate onEndUpdateBookDelegate;
    
    private System.Threading.SendOrPostCallback onUpdateBookCompletedDelegate;
    
    private BeginOperationDelegate onBeginDeleteBookDelegate;
    
    private EndOperationDelegate onEndDeleteBookDelegate;
    
    private System.Threading.SendOrPostCallback onDeleteBookCompletedDelegate;
    
    private BeginOperationDelegate onBeginCreateBookDelegate;
    
    private EndOperationDelegate onEndCreateBookDelegate;
    
    private System.Threading.SendOrPostCallback onCreateBookCompletedDelegate;
    
    private BeginOperationDelegate onBeginLoginDelegate;
    
    private EndOperationDelegate onEndLoginDelegate;
    
    private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public BooksClient()
    {
    }
    
    public BooksClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BooksClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BooksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BooksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<GetBooksCompletedEventArgs> GetBooksCompleted;
    
    public event System.EventHandler<GetBookCompletedEventArgs> GetBookCompleted;
    
    public event System.EventHandler<SearchCompletedEventArgs> SearchCompleted;
    
    public event System.EventHandler<UpdateBookCompletedEventArgs> UpdateBookCompleted;
    
    public event System.EventHandler<DeleteBookCompletedEventArgs> DeleteBookCompleted;
    
    public event System.EventHandler<CreateBookCompletedEventArgs> CreateBookCompleted;
    
    public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBooks.BeginGetBooks(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetBooks(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    BookClient.Data.Book[] IBooks.EndGetBooks(System.IAsyncResult result)
    {
        return base.Channel.EndGetBooks(result);
    }
    
    private System.IAsyncResult OnBeginGetBooks(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IBooks)(this)).BeginGetBooks(callback, asyncState);
    }
    
    private object[] OnEndGetBooks(System.IAsyncResult result)
    {
        BookClient.Data.Book[] retVal = ((IBooks)(this)).EndGetBooks(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetBooksCompleted(object state)
    {
        if ((this.GetBooksCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetBooksCompleted(this, new GetBooksCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetBooksAsync()
    {
        this.GetBooksAsync(null);
    }
    
    public void GetBooksAsync(object userState)
    {
        if ((this.onBeginGetBooksDelegate == null))
        {
            this.onBeginGetBooksDelegate = new BeginOperationDelegate(this.OnBeginGetBooks);
        }
        if ((this.onEndGetBooksDelegate == null))
        {
            this.onEndGetBooksDelegate = new EndOperationDelegate(this.OnEndGetBooks);
        }
        if ((this.onGetBooksCompletedDelegate == null))
        {
            this.onGetBooksCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBooksCompleted);
        }
        base.InvokeAsync(this.onBeginGetBooksDelegate, null, this.onEndGetBooksDelegate, this.onGetBooksCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBooks.BeginGetBook(string isbn, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetBook(isbn, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    BookServer.Services.GetBookResponse IBooks.EndGetBook(System.IAsyncResult result)
    {
        return base.Channel.EndGetBook(result);
    }
    
    private System.IAsyncResult OnBeginGetBook(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string isbn = ((string)(inValues[0]));
        return ((IBooks)(this)).BeginGetBook(isbn, callback, asyncState);
    }
    
    private object[] OnEndGetBook(System.IAsyncResult result)
    {
        BookServer.Services.GetBookResponse retVal = ((IBooks)(this)).EndGetBook(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetBookCompleted(object state)
    {
        if ((this.GetBookCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetBookCompleted(this, new GetBookCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetBookAsync(string isbn)
    {
        this.GetBookAsync(isbn, null);
    }
    
    public void GetBookAsync(string isbn, object userState)
    {
        if ((this.onBeginGetBookDelegate == null))
        {
            this.onBeginGetBookDelegate = new BeginOperationDelegate(this.OnBeginGetBook);
        }
        if ((this.onEndGetBookDelegate == null))
        {
            this.onEndGetBookDelegate = new EndOperationDelegate(this.OnEndGetBook);
        }
        if ((this.onGetBookCompletedDelegate == null))
        {
            this.onGetBookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBookCompleted);
        }
        base.InvokeAsync(this.onBeginGetBookDelegate, new object[] {
                    isbn}, this.onEndGetBookDelegate, this.onGetBookCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBooks.BeginSearch(string searchText, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSearch(searchText, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    BookClient.Data.Book[] IBooks.EndSearch(System.IAsyncResult result)
    {
        return base.Channel.EndSearch(result);
    }
    
    private System.IAsyncResult OnBeginSearch(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string searchText = ((string)(inValues[0]));
        return ((IBooks)(this)).BeginSearch(searchText, callback, asyncState);
    }
    
    private object[] OnEndSearch(System.IAsyncResult result)
    {
        BookClient.Data.Book[] retVal = ((IBooks)(this)).EndSearch(result);
        return new object[] {
                retVal};
    }
    
    private void OnSearchCompleted(object state)
    {
        if ((this.SearchCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.SearchCompleted(this, new SearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void SearchAsync(string searchText)
    {
        this.SearchAsync(searchText, null);
    }
    
    public void SearchAsync(string searchText, object userState)
    {
        if ((this.onBeginSearchDelegate == null))
        {
            this.onBeginSearchDelegate = new BeginOperationDelegate(this.OnBeginSearch);
        }
        if ((this.onEndSearchDelegate == null))
        {
            this.onEndSearchDelegate = new EndOperationDelegate(this.OnEndSearch);
        }
        if ((this.onSearchCompletedDelegate == null))
        {
            this.onSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCompleted);
        }
        base.InvokeAsync(this.onBeginSearchDelegate, new object[] {
                    searchText}, this.onEndSearchDelegate, this.onSearchCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBooks.BeginUpdateBook(BookClient.Data.Book book, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUpdateBook(book, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    BookServer.Services.BooksResponse IBooks.EndUpdateBook(System.IAsyncResult result)
    {
        return base.Channel.EndUpdateBook(result);
    }
    
    private System.IAsyncResult OnBeginUpdateBook(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        BookClient.Data.Book book = ((BookClient.Data.Book)(inValues[0]));
        return ((IBooks)(this)).BeginUpdateBook(book, callback, asyncState);
    }
    
    private object[] OnEndUpdateBook(System.IAsyncResult result)
    {
        BookServer.Services.BooksResponse retVal = ((IBooks)(this)).EndUpdateBook(result);
        return new object[] {
                retVal};
    }
    
    private void OnUpdateBookCompleted(object state)
    {
        if ((this.UpdateBookCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.UpdateBookCompleted(this, new UpdateBookCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void UpdateBookAsync(BookClient.Data.Book book)
    {
        this.UpdateBookAsync(book, null);
    }
    
    public void UpdateBookAsync(BookClient.Data.Book book, object userState)
    {
        if ((this.onBeginUpdateBookDelegate == null))
        {
            this.onBeginUpdateBookDelegate = new BeginOperationDelegate(this.OnBeginUpdateBook);
        }
        if ((this.onEndUpdateBookDelegate == null))
        {
            this.onEndUpdateBookDelegate = new EndOperationDelegate(this.OnEndUpdateBook);
        }
        if ((this.onUpdateBookCompletedDelegate == null))
        {
            this.onUpdateBookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateBookCompleted);
        }
        base.InvokeAsync(this.onBeginUpdateBookDelegate, new object[] {
                    book}, this.onEndUpdateBookDelegate, this.onUpdateBookCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBooks.BeginDeleteBook(string isbn, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteBook(isbn, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    BookServer.Services.BooksResponse IBooks.EndDeleteBook(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteBook(result);
    }
    
    private System.IAsyncResult OnBeginDeleteBook(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string isbn = ((string)(inValues[0]));
        return ((IBooks)(this)).BeginDeleteBook(isbn, callback, asyncState);
    }
    
    private object[] OnEndDeleteBook(System.IAsyncResult result)
    {
        BookServer.Services.BooksResponse retVal = ((IBooks)(this)).EndDeleteBook(result);
        return new object[] {
                retVal};
    }
    
    private void OnDeleteBookCompleted(object state)
    {
        if ((this.DeleteBookCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.DeleteBookCompleted(this, new DeleteBookCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void DeleteBookAsync(string isbn)
    {
        this.DeleteBookAsync(isbn, null);
    }
    
    public void DeleteBookAsync(string isbn, object userState)
    {
        if ((this.onBeginDeleteBookDelegate == null))
        {
            this.onBeginDeleteBookDelegate = new BeginOperationDelegate(this.OnBeginDeleteBook);
        }
        if ((this.onEndDeleteBookDelegate == null))
        {
            this.onEndDeleteBookDelegate = new EndOperationDelegate(this.OnEndDeleteBook);
        }
        if ((this.onDeleteBookCompletedDelegate == null))
        {
            this.onDeleteBookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteBookCompleted);
        }
        base.InvokeAsync(this.onBeginDeleteBookDelegate, new object[] {
                    isbn}, this.onEndDeleteBookDelegate, this.onDeleteBookCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBooks.BeginCreateBook(BookClient.Data.Book book, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginCreateBook(book, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    BookServer.Services.CreateBookResponse IBooks.EndCreateBook(System.IAsyncResult result)
    {
        return base.Channel.EndCreateBook(result);
    }
    
    private System.IAsyncResult OnBeginCreateBook(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        BookClient.Data.Book book = ((BookClient.Data.Book)(inValues[0]));
        return ((IBooks)(this)).BeginCreateBook(book, callback, asyncState);
    }
    
    private object[] OnEndCreateBook(System.IAsyncResult result)
    {
        BookServer.Services.CreateBookResponse retVal = ((IBooks)(this)).EndCreateBook(result);
        return new object[] {
                retVal};
    }
    
    private void OnCreateBookCompleted(object state)
    {
        if ((this.CreateBookCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CreateBookCompleted(this, new CreateBookCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CreateBookAsync(BookClient.Data.Book book)
    {
        this.CreateBookAsync(book, null);
    }
    
    public void CreateBookAsync(BookClient.Data.Book book, object userState)
    {
        if ((this.onBeginCreateBookDelegate == null))
        {
            this.onBeginCreateBookDelegate = new BeginOperationDelegate(this.OnBeginCreateBook);
        }
        if ((this.onEndCreateBookDelegate == null))
        {
            this.onEndCreateBookDelegate = new EndOperationDelegate(this.OnEndCreateBook);
        }
        if ((this.onCreateBookCompletedDelegate == null))
        {
            this.onCreateBookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateBookCompleted);
        }
        base.InvokeAsync(this.onBeginCreateBookDelegate, new object[] {
                    book}, this.onEndCreateBookDelegate, this.onCreateBookCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBooks.BeginLogin(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginLogin(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IBooks.EndLogin(System.IAsyncResult result)
    {
        return base.Channel.EndLogin(result);
    }
    
    private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IBooks)(this)).BeginLogin(callback, asyncState);
    }
    
    private object[] OnEndLogin(System.IAsyncResult result)
    {
        string retVal = ((IBooks)(this)).EndLogin(result);
        return new object[] {
                retVal};
    }
    
    private void OnLoginCompleted(object state)
    {
        if ((this.LoginCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void LoginAsync()
    {
        this.LoginAsync(null);
    }
    
    public void LoginAsync(object userState)
    {
        if ((this.onBeginLoginDelegate == null))
        {
            this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
        }
        if ((this.onEndLoginDelegate == null))
        {
            this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
        }
        if ((this.onLoginCompletedDelegate == null))
        {
            this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
        }
        base.InvokeAsync(this.onBeginLoginDelegate, null, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IBooks CreateChannel()
    {
        return new BooksClientChannel(this);
    }
    
    private class BooksClientChannel : ChannelBase<IBooks>, IBooks
    {
        
        public BooksClientChannel(System.ServiceModel.ClientBase<IBooks> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginGetBooks(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("GetBooks", _args, callback, asyncState);
            return _result;
        }
        
        public BookClient.Data.Book[] EndGetBooks(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            BookClient.Data.Book[] _result = ((BookClient.Data.Book[])(base.EndInvoke("GetBooks", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetBook(string isbn, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = isbn;
            System.IAsyncResult _result = base.BeginInvoke("GetBook", _args, callback, asyncState);
            return _result;
        }
        
        public BookServer.Services.GetBookResponse EndGetBook(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            BookServer.Services.GetBookResponse _result = ((BookServer.Services.GetBookResponse)(base.EndInvoke("GetBook", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginSearch(string searchText, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = searchText;
            System.IAsyncResult _result = base.BeginInvoke("Search", _args, callback, asyncState);
            return _result;
        }
        
        public BookClient.Data.Book[] EndSearch(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            BookClient.Data.Book[] _result = ((BookClient.Data.Book[])(base.EndInvoke("Search", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginUpdateBook(BookClient.Data.Book book, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = book;
            System.IAsyncResult _result = base.BeginInvoke("UpdateBook", _args, callback, asyncState);
            return _result;
        }
        
        public BookServer.Services.BooksResponse EndUpdateBook(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            BookServer.Services.BooksResponse _result = ((BookServer.Services.BooksResponse)(base.EndInvoke("UpdateBook", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginDeleteBook(string isbn, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = isbn;
            System.IAsyncResult _result = base.BeginInvoke("DeleteBook", _args, callback, asyncState);
            return _result;
        }
        
        public BookServer.Services.BooksResponse EndDeleteBook(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            BookServer.Services.BooksResponse _result = ((BookServer.Services.BooksResponse)(base.EndInvoke("DeleteBook", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginCreateBook(BookClient.Data.Book book, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = book;
            System.IAsyncResult _result = base.BeginInvoke("CreateBook", _args, callback, asyncState);
            return _result;
        }
        
        public BookServer.Services.CreateBookResponse EndCreateBook(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            BookServer.Services.CreateBookResponse _result = ((BookServer.Services.CreateBookResponse)(base.EndInvoke("CreateBook", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginLogin(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
            return _result;
        }
        
        public string EndLogin(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("Login", _args, result)));
            return _result;
        }
    }
}
